"""
explicit float byte-order verification.
"""
import struct
import pytest

from receiver import deserialize_packet, compute_checksum, CHECKSUM_INDEX
from packet_builder import build_full_packet
from cpp_runner import CppRunner, CppExecutableError

try:
    _runner = CppRunner()
    CPP_AVAILABLE = True
    _skip_reason = None
except CppExecutableError as e:
    CPP_AVAILABLE = False
    _skip_reason = str(e)


# Known, hand-computed IEEE-754 single-precision bit patterns, independently
# cross-checked against Python's struct module before being trusted here.
# NOT generated by the code under test — that would make this tautological.
KNOWN_FLOAT32_VECTORS = [
    (0.0,   "00000000"),
    (1.0,   "3f800000"),
    (-1.0,  "bf800000"),
    (2.0,   "40000000"),
    (0.5,   "3f000000"),
    (-0.25, "be800000"),
    (10.0,  "41200000"),
]


@pytest.mark.parametrize("value,expected_hex", KNOWN_FLOAT32_VECTORS)
def test_python_struct_pack_matches_known_ieee754_bytes(value, expected_hex):
    """Python's own big-endian float packing matches the known-correct bytes."""
    actual_hex = struct.pack(">f", value).hex()
    assert actual_hex == expected_hex, (
        f"struct.pack('>f', {value}) produced {actual_hex}, expected {expected_hex}."
    )


@pytest.mark.parametrize("value,expected_hex", KNOWN_FLOAT32_VECTORS)
def test_transmitter_produces_correct_float_bytes(value, expected_hex):
    """
    A real packet, built the same way transmitter.py builds one, has its
    payload bytes (offset 8-11, right after the 8-byte header) match the
    known-correct IEEE-754 representation.
    """
    pkt = build_full_packet(node_id=1, layer_id=1, values=[value])
    payload_hex = pkt[8:12].hex()
    assert payload_hex == expected_hex, (
        f"Packet payload for value={value} was {payload_hex}, expected {expected_hex}."
    )


@pytest.mark.parametrize("value,expected_hex", KNOWN_FLOAT32_VECTORS)
def test_receiver_decodes_known_bytes_back_to_correct_value(value, expected_hex):
    """
    The specific direction the original bug manifested in: KNOWN-correct
    bytes going IN, must produce the correct value coming OUT. Bytes are
    written directly from expected_hex, bypassing Python's own float
    packing entirely, so this doesn't depend on build_full_packet's
    encoding being correct — only receiver.py's decoding.
    """
    pkt = bytearray(build_full_packet(node_id=1, layer_id=1, values=[0.0]))  # placeholder
    pkt[8:12] = bytes.fromhex(expected_hex)

    checksum_input = bytearray(pkt)
    checksum_input[CHECKSUM_INDEX] = 0
    pkt[CHECKSUM_INDEX] = compute_checksum(checksum_input)

    ok, decoded = deserialize_packet(bytes(pkt))
    assert ok, f"packet with known-correct bytes for {value} was rejected: {decoded}"
    assert abs(decoded["values"][0] - value) < 1e-6, (
        f"decoded {decoded['values'][0]}, expected {value} — this is exactly "
        f"the failure signature of the original endianness bug."
    )


@pytest.mark.skipif(not CPP_AVAILABLE, reason=_skip_reason or "C++ executable not found")
@pytest.mark.parametrize("value,expected_hex", KNOWN_FLOAT32_VECTORS)
def test_cpp_produces_correct_float_bytes(value, expected_hex):
    """The REAL C++ serializePacket() also matches the known-correct bytes."""
    result = _runner.serialize(source_address=0x1100, target_layer_id=15,
                                packet_type=0, sequence=0, values=[value])
    assert result["ok"], f"C++ serialize failed for value={value}: {result}"
    payload_hex = result["bytes_hex"][16:24]  # header is 8 bytes = 16 hex chars
    assert payload_hex == expected_hex, (
        f"C++ produced {payload_hex} for value={value}, expected {expected_hex}."
    )


def test_regression_1_0_does_not_decode_as_tiny_denormal():
    """
    Explicit named regression test for the EXACT originally-observed bug:
    1.0 must never decode as ~4.6e-41.
    """
    pkt = build_full_packet(node_id=1, layer_id=1, values=[1.0])
    ok, decoded = deserialize_packet(pkt)
    assert ok
    decoded_value = decoded["values"][0]
    assert decoded_value > 0.5, (
        f"decoded 1.0 as {decoded_value} — if this is ~4.6e-41, the "
        f"endianness bug has REGRESSED."
    )
    assert abs(decoded_value - 1.0) < 1e-6